# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  App_config = debug
  Engine_config = debug

else ifeq ($(config),release)
  App_config = release
  Engine_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := App Engine

.PHONY: all clean help $(PROJECTS) App Engine

all: $(PROJECTS)

App: App

Engine: Engine

App: Engine
ifneq (,$(App_config))
	@echo "==== Building App ($(App_config)) ===="
	@${MAKE} --no-print-directory -C App -f Makefile config=$(App_config)
endif

Engine:
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE} --no-print-directory -C Engine -f Makefile config=$(Engine_config)
endif

clean:
	@${MAKE} --no-print-directory -C App -f Makefile clean
	@${MAKE} --no-print-directory -C Engine -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   App"
	@echo "   Engine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"