# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  engine_config = debug
  app_config = debug
  test_config = debug

else ifeq ($(config),release)
  engine_config = release
  app_config = release
  test_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := engine app test

.PHONY: all clean help $(PROJECTS) App Engine Test

all: $(PROJECTS)

App: app

Engine: engine

Test: test

engine:
ifneq (,$(engine_config))
	@echo "==== Building engine ($(engine_config)) ===="
	@${MAKE} --no-print-directory -C Engine -f Makefile config=$(engine_config)
endif

app: engine
ifneq (,$(app_config))
	@echo "==== Building app ($(app_config)) ===="
	@${MAKE} --no-print-directory -C App -f Makefile config=$(app_config)
endif

test: engine
ifneq (,$(test_config))
	@echo "==== Building test ($(test_config)) ===="
	@${MAKE} --no-print-directory -C Test -f Makefile config=$(test_config)
endif

clean:
	@${MAKE} --no-print-directory -C Engine -f Makefile clean
	@${MAKE} --no-print-directory -C App -f Makefile clean
	@${MAKE} --no-print-directory -C Test -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   engine"
	@echo "   app"
	@echo "   test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"